### PR TITLE
conditional display of quiz- and challenge-buttons over videos

### LINKED ISSUE #49: Hide Quiz/Challenge buttons if there is none
### Bootstrap Academy username

DragonDev1906

### Description

Above a Video there are always the Video, Quiz and Challenge tabs, even if there is no Quiz or Challenge. This makes it a bit difficult to see at a glance whether there are Quizzes/Challenges.

It would be nice if the respective button is hidden (or disabled) and maybe even shows a number indicating how many Quizzes/Questions there are if it is > 0.

### PR DESCRIPTION
**Pull request by Maschga**
## Description
This PR hides the quiz- and/or challenge-button(s) above a video if there isn't any quiz or challenge to show. Otherwise it displays the number of items:

However there is still a bug I am not able to fix. Sometimes the buttons are displayed, sometimes not. Does anyone know more about this problem?

https://github.com/Bootstrap-Academy/frontend/assets/88616799/44ebfdf2-4086-423b-8271-5326c6947c21

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#49

My Bootstrap Academy username: Maschga

### CODE REVIEW

**Comment by Lo10Th** [comment]
I wanted to have a look at the whole thing, but I didn't manage to get there because I have to login. My login details don't work on localhost. I see that you are on localhost and logged in, how did you manage that?

**Comment by Defelo** [comment]
@Lo10Th By default the frontend uses the test instance instead of the production instance. Just create a new account here and use that.

**Comment by Lo10Th** [comment]
Isn't there already a fundamental problem?
There is already a quiz in the course. Why is there a quiz in the course that is not displayed on this page? This error also occurs on the develop-branch.
I have opened an issue about it. Have a look...

https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/63

**Comment by Defelo** [comment]
Superseded by #88

**Pull request closed without merging**
