### PR TITLE
Issue#117: Sorting of self hosted courses

### LINKED ISSUE #117: Sorting of self hosted courses
Self hosted courses will always load the video the user previously accessed.
Example:
Python pentesting.
I click on the course and then on video no. 4, I will get served the first video. Going to video 5 will then load video 4.

### PR DESCRIPTION
**Pull request by BugsSindFeatures**
## Description
The Problem was that the video is rendered before the source of the video changed and the change of the video source didn't lead to a re-render of the video.

Changed key attribute of the video from "activelecture.id" to "videoSRC", so the video is re-rendered every time the video source changes.

In addition, the time span when a new video source is created was extended from 40 Seconds to 4000 Seconds so the Video is not re rendered every 40 Seconds.

I don't know if this will cause problems with the API because I don't know when the video source links expire.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#117

My Bootstrap Academy username: R4bbit

### CODE REVIEW

**Review by Lauritz-Tieste — APPROVED** [review]
Working fine.

**Comment by Chel-Jessen** [comment]
The current setting for [stream_token_ttl](https://github.com/Bootstrap-Academy/skills-ms/blob/a76859e336d58634b2d74eccbcef731914eeec68/api/settings.py#L32) is 8 hours.
I assume you use the "/courses/{course_id}/lectures/{lecture_id}" route [get_mp4_lecture_link](https://github.com/Bootstrap-Academy/skills-ms/blob/a76859e336d58634b2d74eccbcef731914eeec68/api/endpoints/course.py#L166).

**Review by Defelo — CHANGES_REQUESTED** [review]
@BugsSindFeatures Thanks for the PR! One thing to note is that `setInterval` expects its timeout argument to be specified in milliseconds, so you just changed it to about 28 seconds, not 8 hours. However the real problem here is that switching to the new stream token no longer seems to work. After about 28 seconds after starting the video (e.g. [here](https://ab6d8332.academy-preview.pages.dev/courses/pentesting_grundlagen/watch?section=section&lecture=pentesting_1_einleitung&skillID=pentester&subSkillID=grundlagen_des_pentesting)) the video just stops and resets, so this definititely needs to be fixed before this PR can be merged.

**Comment by BugsSindFeatures** [comment]
Thanks for the response! I corrected the argument from seconds to milliseconds. The described problem can be solved by Merging the pull request #289 because then the time will be automatically restored and to fix the problem that the Video stops if the source changed I added some code to prevent that.

**Review by Defelo — APPROVED** [review]

**Comment by TheMorpheus407** [comment]
@BugsSindFeatures  Du darfst mir sehr gerne auch die Rechnung per Mail stellen - alle Infos dazu [hier](https://github.com/Bootstrap-Academy/Bootstrap-Academy/)

Danke fürs mitmachen! Und ich hoffe, du hattest Spaß und machst weiterhin mit :)

**Pull request merged**
