### PR TITLE
Add missing Webinar Information

### LINKED ISSUE #11: Missing webinar information
Webinar entries in the calendar are currently lacking a lot of information (even the description is not displayed). When clicking on the event summary on the bottom right of the page under "Upcoming Events", a dialog should open which contains all relevant information about the webinar.

image

## Acceptance criteria
- [x] When clicking on the webinar summary, a dialog should open, containing the following information:
    - [x] Name
    - [x] Description
    - [x] Skill and parent skill (both with links to the skill tree)
    - [x] Start and end timestamps (and duration)
    - [x] Price
    - [x] Instructor name, avatar and rating
    - [x] Link (if the user has access to the link)
    - [x] Admin link (if the user has access to the admin link)
    - [x] Timestamp when this webinar has been created
    - [x] Number of registered participants and maximum capacity
    - [x] A button to book the webinar (if it is bookable)
- [x] In the webinar summary itself, display the skill *name* instead of its id.

### PR DESCRIPTION
**Pull request by StackSurfer**
## Description

- Added Calendar and Skill-Tree classes.
- Included requested webinar information.
- Implemented an accordion for booking.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#11

My Bootstrap Academy username: Joggl

### CODE REVIEW

**Review by Defelo — CHANGES_REQUESTED** [review]
After booking an event, there is no button to open the event summary dialog again. Maybe we should always open the dialog when the user clicks on the event summary heading.

image

**Comment by StackSurfer** [comment]
Hello @Defelo.
I will try to get the requested changes done by the end of Sunday this week.

**Comment by StackSurfer** [comment]
Good Evening @Defelo.

I just pushed your requested changes.

I also fixed a console warning with the previously used "check" icon (a function to display a check on the left side of a chip component if the event is booked) by adding a new icon and using that instead.

**Review by Defelo — CHANGES_REQUESTED** [review]
1. When logged in as an administrator, only the admin link is displayed, not the normal link.
2. The button to edit the webinar has been removed, so it's not possible anymore to edit or delete an existing webinar.
3. The "Link" button on the top right of the event summary doesn't work anymore.
    image

**Comment by StackSurfer** [comment]
Hello @Defelo. 
I just made the changes to: 

1. Show both links if there are any
2. make the link in the top-right of the summary work again

However i did not come accross the problem of not being able to edit the Event as shown in the following Video.

https://github.com/Bootstrap-Academy/frontend/assets/117248962/6e781210-b977-40ab-8cba-fa8afed20df7

**Comment by Defelo** [comment]
But I can't see this button, even though I have admin privileges (probably because I am not the creator of this webinar?). Also it would be better to display both the "more info" button and the "edit webinar" button if the user is the creator or an administrator.

**Comment by StackSurfer** [comment]
> But I can't see this button, even though I have admin privileges (probably because I am not the creator of this webinar?). Also it would be better to display both the "more info" button and the "edit webinar" button if the user is the creator or an administrator.

Yes thats right. On the way trough this Issue i saw that "isMine" constant was computed by just the admin-link. isMine is used to grant the ability to edit/delete the event. 

`const isMine = computed(() => {
      return !!admin_link.value;
    });`
I tought this was wrong tough and changed it to:
`const isMine = computed(() => {
				return user.value.id === props.data.instructor.id;
			});
`

I will edit it so Owner can also see the summary & grant back full access to the Admins.

**Comment by StackSurfer** [comment]
I just saw that I'm missing the Links to the skill & parent-skill. I will do that today.

**Comment by StackSurfer** [comment]
Okay it should be fine now.

**Review by Defelo — CHANGES_REQUESTED** [review]
Hi, here are a few more issues I've found while testing this:
1. Trying to edit a coaching seems to always result in a 404
2. The info dialog for coachings doesn't look quite right image
3. Same for webinar dialogs 
image
4. 
image

But other than that I think this already looks pretty good :+1:

**Comment by StackSurfer** [comment]
>     1. Trying to edit a coaching seems to always result in a 404


It's quite surprising. Apparently, there is no page for editing or creating this type of event within Coachings. I'm unsure how this oversight occurred. Any attempt to access the page results in a 404 error, indicating that the view literally doesn't exist. Since it doesn't appear to have been deleted, I assume it was simply never created. I will proceed to create a page for editing and creating Coachings.

The function in the profile that indicates to be the one for creating a Coaching looks like this:
Screenshot 2023-11-20 at 21 47 09
This is also one more Indicator that these Views simply just don't exist yet.

Either this pull request is about to become larger, covering the Event-summary part along with createCoaching/editCoaching.vue, or we can split it into two separate pull requests.

**Comment by Defelo** [comment]
We should definitely fix this in a separate pull request. For now you can just hide the edit button for coachings to avoid confusion

**Comment by StackSurfer** [comment]
Okay. The "Edit Coaching"- button is hidden now. I'll start working on the views once I'm done with #88.

**Review by Defelo — APPROVED** [review]

**Pull request merged**
