### PR TITLE
Fix quizzes are not displayed

### LINKED ISSUE #49: Hide Quiz/Challenge buttons if there is none
### Bootstrap Academy username

DragonDev1906

### Description

Above a Video there are always the Video, Quiz and Challenge tabs, even if there is no Quiz or Challenge. This makes it a bit difficult to see at a glance whether there are Quizzes/Challenges.

It would be nice if the respective button is hidden (or disabled) and maybe even shows a number indicating how many Quizzes/Questions there are if it is > 0.

### LINKED ISSUE #63: Quizzes are not displayed on the "Watch Course" page
### What browsers are you seeing the problem on?

Chrome

### What happened?

There is a problem that existing quizzes are not displayed in the "Watch Courses" view under the "Quiz" tab. I will clarify this using the video below. 

https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/70955799/eab84ec8-4f77-4b02-be68-567a78666f7d

Note that the quiz shown in the video does not seem to exist anymore. For a different example, see issue #83 by @RLeo

### PR DESCRIPTION
**Pull request by StackSurfer**
## Description

Quizzes will now be displayed in the lecture if the lecture has quizzes.

After talking to @Maschga, I'll be taking over #43 since it's closely related. Instead of conditionally rendering the buttons, I'll provide more information about whether the course has any more quizzes and where the next one is located, or inform them that there are no more quizzes in this course.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#63
Fixes Bootstrap-Academy/Bootstrap-Academy#49

My Bootstrap Academy username: Joggl

### CODE REVIEW

**Review by Defelo — CHANGES_REQUESTED** [review]
Ok, the quizzes seem to always load now, but the challenges do not anymore (e.g. [here](https://008610e1.academy-preview.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz):
image

Also the counts are'nt correct ([here](https://008610e1.academy-preview.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz)): 
image

**Comment by StackSurfer** [comment]
> Ok, the quizzes seem to always load now, but the challenges do not anymore (e.g. [here](https://008610e1.academy-preview.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz): image
> 
> Also the counts are'nt correct ([here](https://008610e1.academy-preview.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz)): image

For the quizzes, the issue might be resolved in #89. However, I am unsure about the challenges. I couldn't find any challenge responses or create a new challenge. 
Which course did you look up the challenges in? Does this course definitely have challenges? If so, I can take a look at them as well. The only question would be where to do this, since #89 is also closely related to all of this.

**Comment by Defelo** [comment]
There should be two challenges in the first lecture of the Medienkompetenz course: https://bootstrap-academy-frontend.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz

**Comment by StackSurfer** [comment]
Good Evening @Defelo. 
I think it should be fine now. 

- Toggle buttons display the number of Quizzes and Challenges in the current lecture.
- Quizzes and Challenges should be displayed correctly.
- I also added an indicator for Quizzes in upcoming/unseen lectures.

**Comment by StackSurfer** [comment]
I ran into an Issue that would require me to look into API-Doc's. Unfortunately I cannot find/access them, probably because the Migration I guess?

**Comment by Defelo** [comment]
Yes, the api docs are now available at https://api.test.bootstrap.academy/. This is also documented in the [Bootstrap-Academy readme](https://github.com/Bootstrap-Academy/Bootstrap-Academy?tab=readme-ov-file#test-instance)

**Comment by StackSurfer** [comment]
Hello @Defelo!
Sry that it took so long. There was a big Conflict with the Matchings-feature that lead into some bugs. I think this pr might be fine now.

**Review by Defelo — APPROVED** [review]

**Pull request merged**
