### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by josiebytes**
## Description
Translation improvements

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Translation updates (fix/improve or add new translations)

My Bootstrap Academy username: Joshiy13

### CODE REVIEW

**Comment by josiebytes** [comment]
readded translations that have been lost in me previous pr

**Comment by josiebytes** [comment]
improved some translations that didn't look good

**Review by nicok1 — APPROVED** [review]
Mir sind auch ein paar Unstimmigkeiten aufgefallen und das sind definitiv willkommene Verbesserungen.

**Comment by josiebytes** [comment]
@Defelo Is it possible for this pr to be merged soon, so I can finish #29?

**Review by Defelo — APPROVED** [review]

**Pull request merged**
