### PR TITLE
Du-Form in translation #45

### LINKED ISSUE #45: German translations: "Du-Form"
Change the german translations to consistently use the "Du-Form" instead of the "Sie-Form" (https://github.com/orgs/Bootstrap-Academy/discussions/39#discussioncomment-7219595).

### PR DESCRIPTION
**Pull request by josiebytes**
## Description
Changing all Sie-Form to the Du-Form in the translations.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#45

My Bootstrap Academy username: Joshiy13

### CODE REVIEW

**Comment by josiebytes** [comment]
Will need to wait for https://github.com/Bootstrap-Academy/frontend/pull/22 to be merged to continue working on this as there could be conflicting changes in this.

**Comment by Defelo** [comment]
Actually, I would like to merge this one first. Merge conflicts can always be resolved later.

**Comment by josiebytes** [comment]
That also works!

**Comment by josiebytes** [comment]
I have looked at the files again and found that this pr cant be finished without merging #22 first.

**Comment by Defelo** [comment]
@Joshiy13 #22 is merged now.

**Pull request closed without merging**
