### PR TITLE
Attempt to fix markdown KaTeX rendering issue

### PR DESCRIPTION
**Pull request by Jonathan2k19**
## Description
**Disclaimer**: I only tested this with the math shown in the description of `/jobs/b6187b88-a423-4ab4-94d2-e7eba2b0bd25`. It might be that this doesn't work on other sites.

Markdown KaTeX (i.e. math) didn't render correctly for the above-mentioned job.
Relevant input:
```
math: $e^{\pi i}=-1$
$$\sum_{i=1}^\infty i = -rac 1{12}$$
```
Relevant output:
before_katex

There were a few problems:
- The job description seems to contain a unicode character in the description just before `rac`, which caused the shown error.
    - I tried to fix this by cleaning the `tex` input before passing it to `katex.renderToString`.
- The `markdown.ts` file only checked for *display* math which is surrounded by `$$`, but not for *inline* math which is surrounded by `$`.
    - I tried to fix this by rewriting a bit of logic and passing `{ displayMode: isDisplayMath }` to `katex.renderToString`.
- The `markdown.ts` file didn't contain the `katex.min.css`. This can cause KaTeX to render *two* outputs (see [this discussion](https://github.com/KaTeX/KaTeX/discussions/2806)).
    - I imported the said CSS.

Now, the output to the above input looks like:
after_katex

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Related to Bootstrap-Academy/Bootstrap-Academy#76

My Bootstrap Academy username: jonathan123456789

### CODE REVIEW

**Comment by TheMorpheus407** [comment]
This PR implements KaTeX support across various sections—specifically, for **Jobs** and **Challenges**, as demonstrated by the following links:

- [Jobs Example](https://6afe312d.academy-preview.pages.dev/jobs/b6187b88-a423-4ab4-94d2-e7eba2b0bd25)
- [Challenges Example](https://6afe312d.academy-preview.pages.dev/challenges/76d2230d-3a25-4917-886a-c68fffdcac4d/9cd0bdbc-7d02-4f82-b7fa-6f52637212c4?codingChallenge=6f6dc9f1-984f-4bcc-b693-5b6ea41910cd)

Currently, KaTeX rendering does not function as expected in **Quizzes**, which can be seen [here](https://6afe312d.academy-preview.pages.dev/quizzes/solve-ab880801-ddb1-4398-8325-5ad502cadf09?quizzesFrom=quiz&querySubTaskId=810e09a4-83c5-438f-8284-5c1ac334f5d7&taskId=ab880801-ddb1-4398-8325-5ad502cadf09).

If you could update to include quizzes with multiline support as well, we can merge :)

**Comment by Jonathan2k19** [comment]
Hi,
I tried to fix KaTeX for quizes as well.

Before: see [here](https://6afe312d.academy-preview.pages.dev/quizzes/solve-ab880801-ddb1-4398-8325-5ad502cadf09?quizzesFrom=quiz&querySubTaskId=810e09a4-83c5-438f-8284-5c1ac334f5d7&taskId=ab880801-ddb1-4398-8325-5ad502cadf09)
After: see [here](https://efa19fc8.academy-preview.pages.dev/quizzes/solve-ab880801-ddb1-4398-8325-5ad502cadf09?quizzesFrom=quiz&querySubTaskId=810e09a4-83c5-438f-8284-5c1ac334f5d7&taskId=ab880801-ddb1-4398-8325-5ad502cadf09)

I'm not sure if I understood what you meant with "multiline support" correctly.
I interpreted it as "don't truncate the line with `...` if the content exceeds the length" as done previously due to the `class="... clamp line-2"`:
no-multiline

**Review by TheMorpheus407 — DISMISSED** [review]
Seems to be working quite well :) Code is good as well. @Defelo please review and merge if okay

**Review by Defelo — CHANGES_REQUESTED** [review]
On the [challenges page](https://b7dba59e.academy-preview.pages.dev/challenges/all?category=76d2230d-3a25-4917-886a-c68fffdcac4d&challenge=9cd0bdbc-7d02-4f82-b7fa-6f52637212c4) KaTeX rendering still seems to be missing:

image

**Comment by Jonathan2k19** [comment]
> On the [challenges page](https://b7dba59e.academy-preview.pages.dev/challenges/all?category=76d2230d-3a25-4917-886a-c68fffdcac4d&challenge=9cd0bdbc-7d02-4f82-b7fa-6f52637212c4) KaTeX rendering still seems to be missing:

Yeah, I missed that one... Should work now, see [here](https://f9326442.academy-preview.pages.dev/challenges/all/?category=76d2230d-3a25-4917-886a-c68fffdcac4d&challenge=9cd0bdbc-7d02-4f82-b7fa-6f52637212c4).

**Review by Defelo — APPROVED** [review]

**Pull request merged**
