### PR TITLE
Working on #18

### LINKED ISSUE #18: Months are not translated in the profile
### Bootstrap Academy username

Morpheus

### Contact Details

kontakt@the-morpheus.de

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

image

Months are not translated in the profile page https://bootstrap.academy/profile

## Acceptance criteria
- [x] When visiting the profile, the months should be translated in the according language chosen by the user
- [x] When editing the profile, the months should be translated in the according language chosen by the user

### PR DESCRIPTION
**Pull request by FabulousCodingFox**
Possibly fixed #18 by adding translations to timestamp conversions

## Description
#18 describes that months and days of the week were not translated in the frontend. I fixed this problem by having convertDateToTimestamp() return translations as strings instead of 'absolute' strings and then converting them with the vue-l18n context const 't'. However, since I don't have access to the affected subpages in the local dev environment, I couldn't verify if it actually works as intended. Please give me feedback on how to display these pages locally or if the fix worked.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#18

My Bootstrap Academy username:
FabulousFox

### CODE REVIEW

**Comment by Defelo** [comment]
Hi, thank you for working on this! What subpages do you mean that you don't have access to? If you have an account on the [test instance](https://bootstrap-academy-frontend.pages.dev/), I can grant you admin permissions their, which should allow you to access all pages.

**Comment by FabulousCodingFox** [comment]
Hi, i just realised that the dev env account works in the local dev environment. My fix is working as intended.

**Comment by FabulousCodingFox** [comment]
# Before
grafik
# After
grafik

**Comment by FabulousCodingFox** [comment]
# Before
grafik
# After
grafik

**Review by Defelo — APPROVED** [review]

**Pull request merged**
