### PR TITLE
Matchings Creation Completed. Further detail in Pull Request

### LINKED ISSUE #30: Feature: User-Generated Matchings Creation
### Bootstrap Academy username

Morpheus

#### Objective:
To democratize content creation on [bootstrap.academy](https://bootstrap.academy/), we aim to enable users (meeting the level requirement) to craft matchings for specific lectures or skills. This feature would be in line with the existing ability to create Multiple Choice Questions. The backend APIs are already in place for this.

#### Functionality:

- [x] **Creation Interface**:
   - [x] Enhance the "Create Task" button next to each lecture or skill to present an additional option, "Create Matching", alongside the pre-existing "Create Quiz" option.
   - [x] Design an interface that prompts users, upon selecting "Create Matching", to input items and their corresponding matches.
   - [x] Incorporate flexibility so users can introduce as many matching pairs as they deem necessary for the exercise.

- [x] **Database Integration**:
   - [x] Configure the backend to process and store the data when a user finalizes a matching exercise. This data should be associated with the specific lecture or skill in the database.

- [x] **Design & Styling**:
   - [x] Ensure the interface for matching creation harmonizes with the website's existing design aesthetics.

#### User Flow for Creation:

- [x] Upon navigating to a particular lecture or skill, users should find and be able to click the "Create Task" button.
  
- [x] Within the "Create Task" options, users should spot and be able to select the "Matching" option.
  
- [x] A user-friendly interface should allow users to input items and their corresponding matches for the matching exercise.
  
- [x] Post the addition of all required pairs, users should have a clear method to submit the matching.
  
- [x] Once submitted, the database should store the matching, making it accessible for the wider user base to engage with and solve.

#### Dependencies:
- Ensure that the new feature integrates seamlessly with the existing task creation functionalities and the platform's tech stack.

#### Notes:
- Prioritize user-friendliness in the creation interface, ensuring that the process is intuitive and straightforward. This will encourage more users to contribute to content creation.

### PR DESCRIPTION
**Pull request by hamzazeus**
## Description
Completed Matchings Creation in this PR.
Total Files changed. around **20**
Added 2 new libraries nanoid and vuedraggable (These will be used while attempting a matching)

I have Removed Import PropType from some files because they aren't required to import. Also, they will cause errors in some developer's machines when their vsCode default tsLink is enabled and they have installed Volar.

Solved a small bug in file VideoMeta "totalLevel.value = subSkill.level" to calculate total Level.

Updated Button Toggle component and it is more mobile responsive.

updated variable name in SubtaskEditableList for better developer experience and a Good approach for variable naming convention

Translations Added for both English and German.

Success and Error are shown to the user in both languages.

Validations while creating a Matching. 

Best User Experience with add and remove icon right beside matchings

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#30

### CODE REVIEW

**Comment by hamzazeus** [comment]
Hi @Defelo. Here is the PR for matchings. Let me know if there's any improvement needed.

**Comment by hamzazeus** [comment]
Hi!! @Defelo. Is there any progress? Let me know if there's any improvement needed.

**Comment by Defelo** [comment]
Hi @hamzazeus, thanks for the pull request! Unfortunately I couldn't really test this feature since it doesn't seem to be possible to solve matchings at all. For example in the [Medienkompetenz course](https://b286e4d1.academy-preview.pages.dev/courses/medienkompetenz/watch?section=section&lecture=zWHWXOhcyeE&skillID=start&subSkillID=medienkompetenz) I cannot open the matchings I have created there, neither in Brave nor in Firefox, both without any errors on the browser console. And if I'm logged in as a user other than the one who created the matchings, I don't even see the matchings at all. Also, matchings don't seem to appear in the [course overview](https://b286e4d1.academy-preview.pages.dev/courses/medienkompetenz?section=section&lecture=fw67-ichp6w&skillID=start&subSkillID=medienkompetenz) nor in the [skill tree](https://b286e4d1.academy-preview.pages.dev/skill-tree/start/medienkompetenz).

**Comment by hamzazeus** [comment]
Hi @Defelo, I have merged my Solve matchings Pull request with this branch. Now you can test it thoroughly.

**Review by Defelo — CHANGES_REQUESTED** [review]
Hi, I have tested this feature now, and I noticed that the `solution` list that is sent to the backend is not generated correctly when creating the matching:

image

In this case I've tried to create a matching for `A -> X`, `B -> Y`, `C -> Z`, so we should have
```python
left = ["A", "B", "C"]
right = ["Z", "X", "Y"]  # shuffled
solution = [1, 2, 0]
# because:
right[1] == "X"
right[2] == "Y"
right[0] == "Z"
```

Also, the list that is received from the backend when viewing the matching as the creator, is not interpreted correctly, so this also needs to be fixed.

**Comment by hamzazeus** [comment]
Hi. I am shuffling the right array and solution array before saving to the backend because if I don't shuffle them before saving to the backend and do shuffle during solving then users can check the logs/network tab and can see the correct right array because the backend is returning the right array same as saved 😅.  It works fine the way I did it. We can also solve it and it's not causing any issues. Should I not shuffle them? Let me know

**Comment by Defelo** [comment]
You should shuffle the right array, but you have to keep track of the indices for the solution array. See the example in my previous comment for how to construct this array. After creating the matching in this example, I was not able to solve it, because the solution arrays didn't match

**Comment by hamzazeus** [comment]
Let me check.

**Comment by hamzazeus** [comment]
CREATE MATCHING CHECK
you can see here right array is shuffled and the solution array is traced correctly as well. (Ignore the error. It's banned error from backend)
Let me check if there any use case for wrong solution array

**Comment by Defelo** [comment]
Yes, because in this case it doesn't matter whether you go "from left to right" or "from right to left". Try again with an arrangement where at least three options are rotated (like in my example)

**Comment by hamzazeus** [comment]
@Defelo issue solved. Thanks for that out! Is there anything else I missed?

**Comment by StackSurfer** [comment]
> Thanks for that out! Is there anything else I missed?

would you mind adding type annotations to the changes you made? I know the project isn't currently using types much, but I think it would be a good idea to start using them consistently.

**Comment by hamzazeus** [comment]
Hi @JohKei Thanks for the suggestion. Added types for the changes :) 
@Defelo Is there any other change needed?

**Review by Defelo — CHANGES_REQUESTED** [review]
I just tested again, and it still doesn't work, behaving the same as before. Here is another example:

image

In this case, the lists should look like this:
```python
left = ["a", "b", "c", "d", "e"]
right = ["5", "3", "1", "4", "2"]
solution = [2, 4, 1, 3, 0]
# because:
right[2] == "1"
right[4] == "2"
right[1] == "3"
right[3] == "4"
right[0] == "5"
```

**Comment by Usman024** [comment]
Sorry. I didn't get your point. I think the output of the list is correct because
left   =  [a , b , c , d , e , f ]
Right before shuffle= [1 , 2 , 3 , 4 , 5 , 6 ]
Solution before shuffle = [0 , 1 , 2 , 3 , 4 ]

Right after shuffle [5 , 3 , 1 , 4 , 2 ]
Solution after shuffle [4 , 2 , 0 , 3 ,1 ]

So Solution shuffle exactly same as right means 5 was at index 4 and now it's at index 0, so our solution's list also shuffle exactly same

**Comment by hamzazeus** [comment]
left is = [a , b , c , d , e , f ]
Right before shuffle= [1 , 2 , 3 , 4 , 5  ]
Solution before shuffle = [0 , 1 , 2 , 3 , 4 ]

Right after shuffle [5 , 3 , 1 , 4 , 2 ]
Solution after shuffle [4 , 2 , 0 , 3 ,1 ]

So Solution shuffle exactly same as right means 5 was at index 4 and now it's at index 0, so our solution's list also shuffle exactly same
Or I am confused about how to do this.

**Comment by hamzazeus** [comment]
shuffling
Maybe this picture can define what i am trying to say

**Comment by Defelo** [comment]
Yes, but this approach is wrong. Here you get the indices for the left array, but we need the indices for the right array

**Comment by hamzazeus** [comment]
Ahhhh Ok Ok now I get it what i am doing wrong.

**Comment by hamzazeus** [comment]
updated algo for solution
@Defelo 
 I hope this is the way you were talking about for the solution array to be sorted. It's working well and we can solve matching too.

**Review by Defelo — APPROVED** [review]
Yes, that looks a lot better now, thanks!

**Comment by hamzazeus** [comment]
usman? 
@Defelo Thanks for merging. And let cedric know about this you have merged the pull request

**Comment by Lauritz-Tieste** [comment]
@hamzazeus @Defelo 

I think the changes in the **German translation** are **unacceptable**. These urgently need a revision.

Examples:
`de.Matching.SolvedQuizzes` = "Gelöst Quizzes"
`de.Matching.ViewQuizzesForLastViewCourse` = "Quizzes für den letzen View-Kurs anzeigen"
`de.Matching.Excel` = "übertreffen"
`de.Matching.PowerPoint` = "Steckdose"
`de.Matching.Empty` = "Leet"
`de.Matching.NoSubmissionCreated` = "Für diese Coding challengeen wird keine Einreichung erstellt"
`de.Matching.Level` = "eben"
`de.Buttons.GoPremium` = "Gehen Prämie"

**Comment by Defelo** [comment]
@Lauritz-Tieste oh yes, absolutely, thanks for pointing that out! Maybe you could create a pull request to revert/fix these changes? You'd just have to make sure to not break then translations for this new feature

**Comment by Lauritz-Tieste** [comment]
okay, I'll try it.

**Comment by Defelo** [comment]
Thanks!

**Comment by Lauritz-Tieste** [comment]
Short Question: What are this "matchings"?

**Comment by Defelo** [comment]
A new kind of quiz where you have a list of items on the left and another list of items on the right, and for each item on the left you have to find the corresponding/matching item on the right (see the screenshots in this pr). So for example, on the left you could have a list of english words, and on the right a list of german words, and you have to find the correct translations.

**Pull request merged**
