### PR TITLE
Nuxt in404 #125

### LINKED ISSUE #125: Nuxt in 404 page
### Bootstrap Academy username

sfb

### Contact Details

academy@spotlightforbugs.eu

### What browsers are you seeing the problem on?

Other (please specify below)

### What happened?

All browsers

IMG_0907

### PR DESCRIPTION
**Pull request by JoeD84**
## Description
This PR solves the "Nuxt in 404 page #125" Issue.

Basically a Nuxt Default Page was shown because no "error.vue" File existed.

The error.vue File was created like described in the Documentation. [Error Page](https://nuxt.com/docs/getting-started/error-handling#error-page) and [Error.vue](https://nuxt.com/docs/guide/directory-structure/error)

This gives the possibility to create a Custom Error page. The Page is designed to blend into the look of the Boostrap Academy.
It uses the Error-Code and Error-Message properties to display the Error reason.

The Error Code has a small glitch animation. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#125

My Bootstrap Academy username: JoeD

### CODE REVIEW

**Comment by Lauritz-Tieste** [comment]
I think the new 404 page has a very good design choice. 👍

**Comment by Chel-Jessen** [comment]
I would change the _div-title_ to a dynamic error code as the error page can be triggered with other codes than 404. Otherwise this looks good.

**Comment by JoeD84** [comment]
@Chel-Jessen Good find. It would also have broken the animation. I just commited the Version with the fixed title Property.

**Review by Defelo — APPROVED** [review]

**Comment by TheMorpheus407** [comment]
@JoeD84  Du darfst mir sehr gerne auch die Rechnung per Mail stellen - alle Infos dazu [hier](https://github.com/Bootstrap-Academy/Bootstrap-Academy/)

Danke fürs mitmachen! Und ich hoffe, du hattest Spaß und machst weiterhin mit :)

**Comment by JoeD84** [comment]
V,@yBN-VDKzhZ*Nmm:3u5gOx:J°°WQ.Gw9BU,M/AVscXM

**Pull request merged**
