### PR TITLE
fix: Prevent infinity loops errors by  validating challengeData 

### LINKED ISSUE #149: Page crash / infinity loop on Challenges page
### Bootstrap Academy username

LauritzTieste

### Contact Details

hello@lauritz-tieste.de

### What browsers are you seeing the problem on?

Other (please specify below)

### What happened?

All Chrome based browsers (here: Vivaldi). Also happening in Chrome, Arc Browser, Brave, MS-Edge

https://github.com/user-attachments/assets/d6a6411a-e297-457b-a640-758394dd278d

I can't explain the error. I noticed it several months ago. There could be an infinity loop somewhere. If you have any questions, just leave a comment. Only happening in the local test instance.

Error message that was spammed about 10,000 times
```
warn [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
  at <Select key=0 label="Category" id="select-category"  ... > 
  at <Challenge data=undefined > 
  at <AsyncComponentWrapper data=undefined > 
  at <Edit[challenge] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {} > > 
  at <Anonymous key="/challenges/edit-9cd0bdbc-7d02-4f82-b7fa-6f52637212c4()" vnode= {} route= {}  ... > 
  at <BaseTransition onAfterLeave= [leer] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [leer] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Inner ref=Ref< Proxy(Object) {} > > 
  at <LayoutLoader key="inner" layoutProps= {} name="inner" > 
  at <NuxtLayoutProvider layoutProps= {} key="inner" name="inner"  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```

### PR DESCRIPTION
**Pull request by eremia2001**
## Description
This pull request fixes a bug in the edit-[challenge].vue component where the challengeData object was not properly initialized and validated. The issue caused methods like .trim() to be called on undefined values, leading to a TypeError. This change ensures that challengeData is properly checked before accessing its properties, thus preventing errors related to undefined attributes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#149

My Bootstrap Academy username: eremiya01

### CODE REVIEW

**Comment by Lauritz-Tieste** [comment]
Good work! It works wonderfully (even without the Nuxt version update).
Unfortunately I don't have the rights to create a review and I can't merge the code.

**Comment by Defelo** [comment]
@eremia2001 why did you change the `package-lock.json`? If the changes there are not required to solve this issue, please revert these changes.

**Comment by eremia2001** [comment]
@Defelo Hey, i had some synching issues thats why .But i am going to revert the changes if its not needed

**Comment by Defelo** [comment]
@Lauritz-Tieste could you test this again please, so we can merge this?

**Comment by eremia2001** [comment]
i also tested it once again. it works as before . I apologize for the mess .

**Comment by Lauritz-Tieste** [comment]
Yeah, everything works! 👍

**Comment by TheMorpheus407** [comment]
@eremia2001 Du darfst mir sehr gerne auch die Rechnung per Mail stellen - alle Infos dazu [hier](https://github.com/Bootstrap-Academy/Bootstrap-Academy/)

Danke fürs mitmachen! Und ich hoffe, du hattest Spaß und machst weiterhin mit :)

**Comment by eremia2001** [comment]
Vielen lieben Dank! ❤️ 
Ich hatte sehr viel Spaß und bedanke mich für die Möglichkeit diese Erfahrung zu sammeln. 
Ich schicke dir bald die Rechnung.

**Comment by eremia2001** [comment]
`SYVFH´RAQ2vX:FKG´gmZoXLvJgq4Gi§V´jf´epvMVJoE

**Pull request merged**
