### PR TITLE
Open quiz page without showing small quizlist

### LINKED ISSUE #105: Skip the small view for the quiz questions in the skill overview
### Bootstrap Academy username

Morpheus

### Description

When in the overview of a skill (eg https://bootstrap.academy/skill-tree/grundlagen_der_programmierung_und_datenhaltung/python_grundlagen) clicking on "Quizzes" will load many many quiz questions. But they cannot be solved there anyways. Instead we should open up the window for all quiz questions (https://bootstrap.academy/quizzes/solve-python_grundlagen?quizzesFrom=skill&querySubTaskId=b03e9474-6646-4747-a82d-3276da3644fa&taskId=cd925718-3cde-45ba-b51a-c19a138fa919&rootSkillID=grundlagen_der_programmierung_und_datenhaltung&subSkillID=python_grundlagen) like it is right now if we would click on the very first one. This click is just unnecessary for the user and it will lead to problems when including more tasks than just quizzes.

### PR DESCRIPTION
**Pull request by Lauritz-Tieste**
## Description
image

Fixes https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/105

My Bootstrap Academy username: Lauritz

### CODE REVIEW

**Comment by Defelo** [comment]
I think it would make sense to also skip this step for matchings

**Comment by Lauritz-Tieste** [comment]
> I think it would make sense to also skip this step for matchings

Good idea, I will look into it and update the PR when I am ready.

**Comment by Lauritz-Tieste** [comment]
Ready.

**Comment by Lauritz-Tieste** [comment]
Can we finish this by merging? 😀

**Review by Defelo — APPROVED** [review]

**Pull request merged**
