### PR TITLE
Add Info about payment methods and processing

### LINKED ISSUE #118: Add Info about payment methods
### Bootstrap Academy username

Morpheus

### Contact Details

_No response_

### What browsers are you seeing the problem on?

_No response_

### What happened?

In the FAQ Section and before buying, there should be an explanation on how to acquire MorphCoin. Specifically a user wanted us to include how to buy them - with PayPal and Credit Card are our only options and we should clarify that.

### PR DESCRIPTION
**Pull request by ghost**
## Description

Adjust hero faq and buy MorphCoins description to clarify the available payment options and processing of the payment.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#118

My Bootstrap Academy username: eeng1n

### CODE REVIEW

**Comment by Lauritz-Tieste** [comment]
I think we should add to the "GetMorphcoins" page that you can also get morphcoins through jobs, webinars, coaches ... So far this is only included in the "HeroFAQS"

**Comment by ghost** [comment]
Do you mean the /morphcoins route? Doesn't this already include the information? Or do you mean adjusting the wording to say that you can get morphcoins through it like in the first one for buying them?

See:
grafik

**Comment by Lauritz-Tieste** [comment]
sorry, just forget it

**Comment by ghost** [comment]
No worries! So could this change be reviewed, or do we need any further adjustments to the change? :)

**Review by Lauritz-Tieste — APPROVED** [review]

**Comment by Lauritz-Tieste** [comment]
Only @Defelo can do the merge :)

**Review by Defelo — APPROVED** [review]

**Pull request merged**
